### ISSUE TITLE
Bitfinex unable to paper trade or real trade

### ISSUE THREAD

**Issue by cl3nk4** [carlos8f/zenbot#1897] opened 2019-06-30 20:23 UTC
### System information
- **Have I written custom code**: No, only touched conf and strategies, and applied #1765 fix during install
- **OS Platform and Distribution)**:Ubuntu 18.04
- **Zenbot version** ): commit 6b246922580af7f455a9596980b374fcc00d631d
- **Zenbot branch**: unstable
- **NodeJS version**: v8.16.0
- **Python version (when using a python script)**: N/A
- **Exact command to reproduce**: `./zenbot.sh trade --paper bitfinex.LTC-USD`
- **Did I make any changes to conf-sample.js?**: added API key for bitfinex

### Describe the problem
After starting paper mode, pre-roll data comes in, and the command lines start as usual, however once it gets to the part where it should start, it gets stuck on the last line of updates, and then never updates data again
If you try to manually buy, it will say not enough balance even though there is clearly enough balance.

Simulations work fine, other exchanges work fine as well

### Source code / Error logs
![nothing](https://user-images.githubusercontent.com/51991472/60401732-1fe39c00-9b75-11e9-8ba7-a6b3950ee466.png)

**Comment by DeviaVir** [comment] 2019-07-03 08:34
Duplicate of https://github.com/DeviaVir/zenbot/issues/1777 ?

**Comment by cl3nk4** [comment] 2019-07-05 06:29
> 
> 
> Duplicate of #1777 ?

It's possible, but I don't see any specific error readings...it just doesn't do anything
Also backfilling and running sim commands work, but it's unable to run paper or real trading

**Comment by Techie-Inc** [comment] 2020-01-05 07:54
Any progress on this? I'm having exactly the same issue.

I can see console updates but always prints the first timestamp line it started paper trading with. Also replaces the line and doesn't move to a new line.

**Comment by fculpo** [comment] 2020-06-22 14:42
probably related to #2223

**Closed as completed** 2020-06-23 07:20 UTC
Labels: bug, exchange, bitfinex
