### ISSUE TITLE
UnhandledPromiseRejectionWarning: MongoNetworkError

### ISSUE THREAD

**Issue by ASullet** [carlos8f/zenbot#2162] opened 2020-05-17 18:00 UTC
### System information
- **Have I written custom code (as opposed to using zenbot vanilla)**: No
- **OS Platform and Distribution (e.g., Linux Ubuntu 16.04)**: OSX 10.15.3 Cataline
- **Zenbot version** (commit ref, or version): d23cf2b
- **Zenbot branch**: unstable 
- **NodeJS version**: 10.16.0
- **Python version (when using a python script)**: 3.7.4
- **Exact command to reproduce (include everything)**: `./zenbot.sh sim binance.BTC-USDT --start="202004010000" --end="202004302359"`
- **Did I make any changes to conf-sample.js?**: No

### Describe the problem

Can't complete the simulation. Having following issue

``` 
(node:87645) UnhandledPromiseRejectionWarning: MongoNetworkError: connection 4 to 127.0.0.1:27017 timed out at (anonymous function).forEach.op (/Users/alex/Desktop/BotTrading/zenbot/node_modules/mongodb/lib/cmap/connection.js:78:15)
    at Map.forEach (<anonymous>)
    at Socket.Connection.stream.on (/Users/alex/Desktop/BotTrading/zenbot/node_modules/mongodb/lib/cmap/connection.js:77:20)
    at Socket.emit (events.js:198:13)
    at Socket._onTimeout (net.js:442:8)
    at ontimeout (timers.js:436:11)
    at tryOnTimeout (timers.js:300:5)
    at listOnTimeout (timers.js:263:5)
    at Timer.processTimers (timers.js:223:10)
(node:87645) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:87645) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

### Source code / Error logs
Include any logs or source code that would be helpful to diagnose the problem. If including tracebacks, please include the full traceback. Large logs and files should be attached. Try to provide a reproducible test case that is the bare minimum necessary to generate the problem.

**Comment by 3DExtended** [comment] 2020-05-21 18:56
I can confirm this error: I just setup ZenBook as of today using the provided docker get started guide and am running into the same issue.

**Comment by louis1204** [comment] 2020-05-25 04:56
Duplicate of #1972
The referenced issue suggests to use node version 12, but I'm seeing the same while running node v12.16.3.

**Closed as completed** 2020-05-25 09:36 UTC
Labels: duplicate, question
