### ISSUE TITLE
How to get a CSV file?

### ISSUE THREAD

**Issue by linuxu678** [carlos8f/zenbot#1995] opened 2020-03-10 12:41 UTC
I execute the command. (./zenbot.sh sim kraken.XXBT-ZEUR --days 30). Finally creates an html file. How to get CSV?

Thanks in advance.

**Comment by LightDelphin** [comment] 2020-03-13 13:15
Тоже интересно, можно ли вывести CSV документ, то что в консоле пишет?

**Comment by DeviaVir** [comment] 2020-03-16 22:51
Make sure you don't have a `filename` set in your conf. You may also want to set `backtester_generation`, that will output a json you could ingest.

**Comment by LightDelphin** [comment] 2020-03-18 08:53
Thanks. I understood approximately. Well, I didn’t succeed, it created empty csv files and several json files. Tell me, please, which command do you need to use in order to display data in csv for the last month? Thanks in advance.

**Comment by linuxu678** [comment] 2020-03-18 08:57
Thanks. I understood approximately. Well, I didn’t succeed, it created empty csv files and several json files. Tell me, please, which command do you need to use in order to display data in csv for the last month? Thanks in advance.

**Comment by duongviethen** [comment] 2020-05-02 00:32
> `
Duplicate of #`

**Closed as completed** 2020-06-23 07:19 UTC
Labels: question
